### ISSUE TITLE
Card

### ISSUE THREAD

**Issue by o1dnik** [moberries/web-lib#17]
Example of a flexible card rendering different content differently.
http://react.semantic-ui.com/views/card
TODO: before creating the Card component a few examples of a real-world usecases should be provided and argumented.

**Comment by dimonnwc3** [comment]
here is an interesting example as well http://www.material-ui.com/#/components/card
see an expandable card

**Comment by o1dnik** [comment]
@dimonnwc3  Still we have to collect a few samples how the component might be used.
