### ISSUE TITLE
Replace bourbon & bitters

### ISSUE THREAD

**Issue by o1dnik** [moberries/web-lib#38]
https://www.npmjs.com/package/bourbon-bitters
https://www.npmjs.com/package/bourbon

```
// @import '../../node_modules/bourbon/app/assets/stylesheets/bourbon';
// @import '../../node_modules/bourbon-bitters/app/assets/stylesheets/bitters';
```
plus
```
// @import '~react-select/dist/react-select.min.css';
// @import '~react-input-range/dist/react-input-range.min.css';
```

**Comment by dimonnwc3** [comment]
I try to install bitters and bourbon from npm, but there is a lot of deprecation warnings and errors
need to be done together with @hypersnob @o1dnik

**Comment by o1dnik** [comment]
we will discuss later this issue alltogether - this is why we need a minimal required styleguide including code samples - it may serve as documentation. "Minify and standardize" (c)
