### ISSUE TITLE
renaming of project

### ISSUE THREAD

**Issue by dimonnwc3** [moberries/web-lib#44]
@azayarni @o1dnik @samihda 
there will be not only components, another shared code as well.
we can rename it to short: 'mo-lib'

**Comment by azayarni** [comment]
ok from my site, but may be web-lib or mo-web-lib

**Comment by o1dnik** [comment]
It doesn't matter as much as renaming the files (ex.: `account-actions.js`). But shorter and more general name is logical.

**Comment by samihda** [comment]
Good idea, I think web-components is no longer an ideal name then. I guess it's also useful to easily disambiguate the name from other (backend) repo names here, so I'd go with Andre's name suggestions.

**Comment by dimonnwc3** [comment]
I'm for mo-web-lib

**Comment by azayarni** [comment]
done
