### ISSUE TITLE
Replace absolute imports with relative

### ISSUE THREAD

**Issue by o1dnik** [moberries/web-lib#62]
this will allow `npm-link`ing and some other things

**Comment by dimonnwc3** [comment]
- [ ] we need to add it to deps as well: `history` `react-router-dom`
- [ ] axios import can be removed from `api-middleware`
- [ ] we can just pass our configured axios instance from our apps to middleware and use it from closure

**Comment by o1dnik** [comment]
https://github.com/moberries/web-lib/commit/c71a841276410f025083839c5a2e6ac6d5f1d889
https://github.com/moberries/web-lib/commit/b332868ac2e485f2762ead7a0354d55e649886a8
https://github.com/moberries/web-lib/commit/d23455db5dd355ed2ecfd15de4c5f7888ca338ed
https://github.com/moberries/web-lib/commit/cb23327154b931f83f5ab63fc17c4f0aab7875fa

**Notes**

To update `web-lib` run `npm run update:components`.

For no-push development of web-lib components follow instructions:

1. run npm link in web-lib project (once)
2. run npm link web-lib in candy/company project (once)
3. start npm run build:watch in web-lib project (it will recompile your code with babel on each change)
4. start candy/company app, you will see all changes immediately

...read more here: https://github.com/moberries/web-lib/wiki/Development-with-candy-company
