### ISSUE TITLE
Placeholder text

### ISSUE THREAD

**Issue by azayarni** [moberries/web-lib#64]
Placeholder text for inout fields and textareas is to dark it looks like already entered text which is confusing. Must be more lighter. 

![screen shot 2017-06-06 at 14 09 05](https://cloud.githubusercontent.com/assets/926368/26828522/1db72bdc-4ac2-11e7-83b2-1bcb4849bb2b.png)

**Comment by dimonnwc3** [comment]
@azayarni landed on dev
