### ISSUE TITLE
Storybook deployment

### ISSUE THREAD

**Issue by azayarni** [moberries/web-lib#66]
I've created a s3 bucket and configured it as web server.
http://weblib.moberries.com.s3-website.eu-central-1.amazonaws.com/

For deployment static files can be just copied to the bucket. No need for cloudfront caching.

**Comment by dimonnwc3** [comment]
use surge.sh

**Comment by dimonnwc3** [comment]
@azayarni it's done under http://styleguide.moberries.com/
with surge.sh

s3 bucket can be removed

**Comment by dimonnwc3** [comment]
@o1dnik FYI
