### ISSUE TITLE
Job selector issues

### ISSUE THREAD

**Issue by azayarni** [moberries/web-lib#67]
- [x]  The selector opens with focus on first option. Because of this the title of the first category "Software Development" is not visible without scrolling up. 

![screen shot 2017-06-15 at 12 01 23](https://user-images.githubusercontent.com/926368/27176418-b9c2da1a-51c2-11e7-8b3f-bb6a53e3680a.png)

- [x] The "x" sign is showing even, when nothing is selected.

**Comment by o1dnik** [comment]
Let it be here
https://github.com/JedWatson/react-select/issues/59
https://github.com/HubSpot/react-select-plus/

**Comment by dimonnwc3** [comment]
@azayarni landed on dev

**Comment by azayarni** [comment]
Works for me 👍
