### ISSUE TITLE
Modals layout

### ISSUE THREAD

**Issue by yuliiad** [moberries/web-lib#70]
![2017-07-26_155908](https://user-images.githubusercontent.com/25003898/28625069-702817fc-721b-11e7-9828-5c8bd79d1bed.png)

**Comment by azayarni** [comment]
Additionally please adjust the layout, it is so much empty space on the sides. Let it may be look more like https://getbootstrap.com/docs/4.0/components/modal/

**Comment by azayarni** [comment]
buttons should be aligned to the right. @hypersnob 

![screen shot 2018-01-12 at 18 08 50](https://user-images.githubusercontent.com/926368/34935679-f71e8c00-f9de-11e7-93aa-c9bc9ffb1f3e.png)

**Comment by hypersnob** [comment]
@azayarni @yuliiad
Please check

**Comment by yuliiad** [comment]
checked on dev
candidate 
![2018-01-16_152041](https://user-images.githubusercontent.com/25003898/34993522-de75c6f8-fad0-11e7-97a2-8b62dc49ce36.jpg)

company
![2018-01-16_152014](https://user-images.githubusercontent.com/25003898/34993525-e36ec77c-fad0-11e7-87d2-8fe5598e5bbd.jpg)

don't see changes yet

**Comment by hypersnob** [comment]
@yuliiad sure you are in the right branch? ft_#70_modals_layout
![modal-desktop](https://user-images.githubusercontent.com/951542/34998687-0afc837e-fae0-11e7-8c9d-4a2240c1ff7c.png)

**Comment by azayarni** [comment]
needs to be merged into master.

**Comment by yuliiad** [comment]
@hypersnob I'm out of the branches, sometimes I feel myself like I'm out of the universe.

tested. ok here, can be merged to staging @dimonnwc3

**Comment by dimonnwc3** [comment]
@yuliiad done

**Comment by yuliiad** [comment]
ok here
