### ISSUE TITLE
long name of JD on the dashboard IE 11

### ISSUE THREAD

**Issue by yuliiad** [moberries/web-lib#71]
The same problem on candy app and company app:
![2017-09-22_104613](https://user-images.githubusercontent.com/25003898/30740196-558cff78-9f90-11e7-8081-2db57cd100d5.jpg)
![2017-09-22_104658](https://user-images.githubusercontent.com/25003898/30740197-5594ab38-9f90-11e7-85e6-cadf846d70fc.jpg)
![2017-09-22_121615](https://user-images.githubusercontent.com/25003898/30740198-559650b4-9f90-11e7-93bc-c8b5d9fa5cb9.jpg)

**Comment by azayarni** [comment]
@yuliiad please check if still present on new dashboard and in case assign to Oleg

**Comment by yuliiad** [comment]
@azayarni yes it's still actual

![2018-01-15_101200](https://user-images.githubusercontent.com/25003898/34935236-79f132f6-f9dd-11e7-89a6-faca2a50b963.jpg)
![2018-01-15_101214](https://user-images.githubusercontent.com/25003898/34935238-7a09de82-f9dd-11e7-890a-4a8d225e4bc0.jpg)
![unnamed](https://user-images.githubusercontent.com/25003898/34935239-7a21cb3c-f9dd-11e7-8858-79a92f500467.png)

**Comment by yuliiad** [comment]
@hypersnob requested credentials
Company app
https://staging-my.moberries.com/
yuliia+test2209man2st@moberries.com
12345678

Candidate app
https://staging-app.moberries.com/
yuliia+test0201can1st@moberries.com
12345678

**Comment by yuliiad** [comment]
the requested statistic for using IE on the apps:
since 1st October 1.59% of users were using IE
94% of those the latest version
