### ISSUE TITLE
Maximal number of request retries

### ISSUE THREAD

**Issue by azayarni** [moberries/web-lib#73]
On a request failure while saving the form data, only a maximal number of 3 (?) retry requests should be sent.

**Comment by o1dnik** [comment]
@dimonnwc3 @azayarni as discussed, current ticket is not relevant anymore, so I'm creating another one related to the issue (to reset input value to previous on failure of live-update) in according app repo.
https://github.com/moberries/web-company-app/issues/284
https://github.com/moberries/web-candidate-app/issues/284
