### ISSUE TITLE
error codes adjustments

### ISSUE THREAD

**Issue by dimonnwc3** [moberries/web-lib#77]

**Comment by scheparev-moberries** [comment]
Custom first level errors from will be removed/replaced due to standard mapping.
Like following:
was
```
400
{
    "code": "no_accepted_match_error",
    ...
}
```
will be 
```
{
    "code": "validation_error" // universal mapping of http status code to the error code,
    "non_field_errors":[
        {"code": "no_accepted_company_match", ...}, ... // note that the code can be different, will supply the mapping in the next comment
    ]
}
```

**Comment by scheparev-moberries** [comment]
first level error -> non_field_errors error:
no_accepted_match_error -> no_accepted_company_match
candidate_start_thread_error -> candidate_start_thread_attempt
not_participant_error -> invalid_author

maybe more would come

**Comment by dimonnwc3** [comment]
@scheparev-moberries we have none of them, probably these cases hard to reproduce from UI and we have never met them before
please add next errors to new message
