### ISSUE TITLE
add popovers

### ISSUE THREAD

**Issue by dimonnwc3** [moberries/web-lib#88]

**Comment by dimonnwc3** [comment]
@yuliiad @azayarni functionality could be checked here
http://styleguide.moberries.com/?selectedKind=Popover&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

needs styling @hypersnob

**Comment by dimonnwc3** [comment]
styles are here as well

**Comment by yuliiad** [comment]
looks like warning message with this red font and red line @azayarni did you see it?
![2018-01-18_105838](https://user-images.githubusercontent.com/25003898/35092110-ab200434-fc3e-11e7-8c4e-a3d882d53882.jpg)

**Comment by dimonnwc3** [comment]
- support for colors like alertbar
- add styles for icon for input label

**Comment by dimonnwc3** [comment]
@yuliiad changed

**Comment by dimonnwc3** [comment]
@hypersnob 
change max width
change headers to be always black

@yuliiad add info please

**Comment by yuliiad** [comment]
- [ ] I'm  requesting to make titles on popovers black, bcs we are not using blue titles on the platform anywhere. 

- [ ] I'm  also requesting to make them smaller -> 350px.

**Comment by dimonnwc3** [comment]
@yuliiad its done
